import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

import { Instrument_Sans } from "next/font/google";

import { IconSprite } from "@/components";

import "./normalize.css";
import "./globals.scss";
import styles from "./layout.module.scss";

export const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-family",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={instrumentSans.variable}>
        <main className={styles.main}>{children}</main>
        <IconSprite />
      </body>
    </html>
  );
}
